#!/usr/bin/env bash
# adding EndeavourOS repo and configs and setup arch-docker to work for EndeavourOS
# may switch to a real EndeavourOS docker image soon

pacman-key --init && pacman -Syu --noconfirm && pacman -Syu base-devel --noconfirm
pacman -Sy --noconfirm --needed archlinux-keyring wget
wget https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-ISO/main/pacman.conf
cp pacman.conf /etc/pacman.conf
wget https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-ISO/main/airootfs/etc/makepkg.conf
cp makepkg.conf /etc/makepkg.conf
wget https://raw.githubusercontent.com/endeavouros-team/PKGBUILDS/master/endeavouros-mirrorlist/endeavouros-mirrorlist
cp endeavouros-mirrorlist /etc/pacman.d/endeavouros-mirrorlist
pacman-key --recv-key 0F20FADC599D1C46EB556455AED8858E4B9813F1 --keyserver keyserver.ubuntu.com && pacman-key --lsign-key 0F20FADC599D1C46EB556455AED8858E4B9813F1
pacman-key --recv-key 497AF50C92AD2384C56E1ACA003DB8B0CB23504F --keyserver keyserver.ubuntu.com && pacman-key --lsign-key 497AF50C92AD2384C56E1ACA003DB8B0CB23504F
pacman-key --init
pacman -Syy --noconfirm endeavouros-keyring 
pacman -S --noconfirm endeavouros-mirrorlist
pacman -S --noconfirm reflector eos-rankmirrors
reflector --age 2 --number 23 --save /etc/pacman.d/mirrorlist
eos-rankmirrors —verbose —sort rate

# install dependencies to build calamares
pacman -S --noconfirm --needed git cmake extra-cmake-modules python-jsonschema python-pyaml python-unidecode gawk qt6-svg qt6-webengine yaml-cpp networkmanager upower kcoreaddons kconfig ki18n kservice kpmcore kwidgetsaddons  squashfs-tools rsync pybind11 cryptsetup doxygen dmidecode gptfdisk hwinfo kparts polkit-qt6 python solid qt6-tools libpwquality ckbcomp qt6-declarative
