name: build Calamares installer package for EndeavourOS

on:
  schedule:
    - cron: "0 9-23/5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2
                      
      - name: Add EndeavourOS Repo
        run: bash add-EndeavourOS
        
      - name: Build Calamares package
        run: bash calamares-build

      - name: Set package name as env
        run: echo "PKG=$(ls /home/build/calamares-git | grep .pkg.tar.zst)" >> $GITHUB_ENV
        
      - name: Rename to latest 
        run: mv /home/build/calamares-git/${{ env.PKG }} /home/build/calamares-git/calamares-git-latest-any.pkg.tar.zst
         
      - name: Upload binaries to release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN_GITHUB }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Calamares EndeavourOS development package [${{ env.PKG }}]"
          files: /home/build/calamares-git/calamares-git-latest-any.pkg.tar.zst
          remove_assets: true
